#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

dunst &
redshift -m vidmode:screen=0 &
redshift -m vidmode:screen=1 &
redshift -m vidmode:screen=2 &
redshift -m vidmode:screen=3 &

exec awesome
